### ISSUE TITLE
npm install core-js not fixing issue

### ISSUE THREAD

**Issue by sup95** [bugsnag/kotlin-multiplatform-example#2]
Hi!
The Kotlin multiplatform example looks great! :)

I have been trying to run the repo locally, and have been having troubles with running the js-app locally.
I did an "npm install core-js" at the root level, js-app/build level, and tried in a few other directory levels too. But I still have these errors:
`Module not found: Error: Can't resolve 'core-js/library/fn/object/assign' `
`Uncaught Error: Cannot find module 'core-js/library/fn/object/assign'`

Should I be doing the npm install some place else?

Thanks!

**Comment by fractalwrench** [comment]
Hi @sup95 - it's been a while since I looked at this one but I believe it'd need to be done in the `js-app` module, which contains the `node_modules`

**Comment by sup95** [comment]
Thank you! I had tried that, and it hadn't worked for me. I realized that the problem was that `npm install core-js` fetches the latest version i.e 3.0.0, while this project uses 2.6.3.
`npm install core-js@2.6.4` worked. :)

**Comment by fractalwrench** [comment]
Glad to hear you resolved the issue!
