### ISSUE TITLE
(not really an Issue) You should put link to article on README

### ISSUE THREAD

**Issue by mwolfson** [bugsnag/kotlin-multiplatform-example#4]
I really love this example, and the [writeup](https://www.bugsnag.com/blog/kotlin-multiplatform), you did about this.  

I suggest you add a link to your writeup on the README, so people who find this, will be able to learn from it. 

Thanks again for the great repo, it is super useful.

**Comment by fractalwrench** [comment]
Thanks for the kind words @mwolfson - glad to hear you're finding this repo useful. I've updated the README with a link to the blog post.
